# INDICES
READ:
  - "indices:data/read*"
WRITE:
  - "indices:data/write*"
CRUD:
  - READ
  - WRITE
CREATE_INDEX:
  - "indices:admin/create*"
DELETE_INDEX:
  - "indices:admin/delete*"
INDEX_OWNER:
  - CREATE_INDEX
  - CRUD
INDEX_ALL:
  - "indices:*"

# ELASTICSEARCH ENTRYPOINT
GET_TEMPLATE:
  - "indices:admin/template/get"
PUT_TEMPLATE:
  - "indices:admin/template/put"
TEMPLATE_OWNER:
  - GET_TEMPLATE
  - PUT_TEMPLATE
ES_INPUT:
  - TEMPLATE_OWNER
  - WRITE

# MONITORING
MONITOR:
  - "cluster:monitor/*"
  - "cluster:admin/ingest/*"
  - "cluster:admin/xpack/*"
  - "indices:data/read/mget*"
  - "indices:data/read/msearch*"
  

#SNAPSHOTS
MANAGE_SNAPSHOTS:
  - "cluster:admin/repository*"
  - "cluster:admin/snapshot*"

# SUPER POWERS
ALL:
  - "*"
